/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Cristhian Urbina
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(706, 720));
        setMinimumSize(new java.awt.Dimension(706, 720));
        setPreferredSize(new java.awt.Dimension(706, 720));
        getContentPane().setLayout(null);

        jLabel1.setText("1.- Ingresar datos de N cursos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 210, 174, 16);

        jLabel2.setText("2.- Reportar todos los datos de los cursos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 240, 239, 16);

        jLabel3.setText("3.- Agregar datos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 280, 101, 16);

        jLabel4.setText("4.- Modificar datos de los cursos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 310, 186, 16);

        jLabel5.setText("5.- Eliminar datos de los cursos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 340, 180, 16);

        jLabel6.setText("6.- Consultar por nombre de curso");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 380, 198, 16);

        jLabel7.setText("7.- Consultar por ciclo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 410, 126, 16);

        jLabel8.setText("8.- Ordenar los datos alfabéticamente");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 450, 217, 16);

        jLabel9.setText("9.- Ordenar en forma descendente en base al ciclo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 490, 291, 16);

        jLabel10.setText("10.-Realizar la matrícula de un alumno");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 520, 222, 16);

        jLabel11.setText("11.- Reportar todos los datos de los NT registros realizados");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 560, 341, 16);

        jLabel12.setText("12.-Terminar");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 590, 76, 16);

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Opc 2");
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 240, 150, 25);

        jButton2.setBackground(new java.awt.Color(51, 0, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Opc 3");
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 270, 150, 25);

        jButton3.setBackground(new java.awt.Color(51, 0, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Opc 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 210, 150, 25);

        jButton4.setBackground(new java.awt.Color(51, 0, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Opc 5");
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 340, 150, 25);

        jButton5.setBackground(new java.awt.Color(51, 0, 153));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Opc 6");
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 380, 150, 25);

        jButton6.setBackground(new java.awt.Color(51, 0, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Opc 4");
        getContentPane().add(jButton6);
        jButton6.setBounds(400, 310, 150, 25);

        jButton7.setBackground(new java.awt.Color(51, 0, 153));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Opc 8");
        getContentPane().add(jButton7);
        jButton7.setBounds(400, 450, 150, 25);

        jButton8.setBackground(new java.awt.Color(51, 0, 153));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Opc 9");
        getContentPane().add(jButton8);
        jButton8.setBounds(400, 490, 150, 25);

        jButton9.setBackground(new java.awt.Color(51, 0, 153));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Opc 7");
        getContentPane().add(jButton9);
        jButton9.setBounds(400, 410, 150, 25);

        jButton10.setBackground(new java.awt.Color(51, 0, 153));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Opc 11");
        getContentPane().add(jButton10);
        jButton10.setBounds(400, 560, 150, 25);

        jButton12.setBackground(new java.awt.Color(51, 0, 153));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Opc 10");
        getContentPane().add(jButton12);
        jButton12.setBounds(400, 530, 150, 25);

        jButton11.setBackground(new java.awt.Color(51, 0, 153));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Opc 12");
        getContentPane().add(jButton11);
        jButton11.setBounds(400, 590, 150, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel13.setText("Menú Principal");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(220, 120, 150, 25);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maxresdefault.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 670, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
