/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidad.UCurso;

/**
 *
 * @author Frequena Chuyes
 */
public class VCurso extends javax.swing.JFrame {

    /**
     * Creates new form VCurso
     */
    private int correcto=1;
    private String idcurso=null;
    private String nombre=null;
    private int ncredito=0;
    private int ciclo=0;
    private String prerequisito=null;
    private UCurso ucurso=new UCurso();
    private DefaultTableModel table;
    private String col[] = {"N°","IdCurso","Nombre","N° Credito", "Ciclo", "Pre-Requisito"};
    private int index=-1;
    
    public VCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("Ordenar por Nombre");
        jMenuItem1.setComponentPopupMenu(jPopupMenu1);
        jMenuItem1.setName("jmxnombre"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ordenar por Ciclo");
        jMenuItem2.setComponentPopupMenu(jPopupMenu1);
        jMenuItem2.setName("jmiciclo"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos Curso");

        jLabel2.setText("Cod :");
        jLabel2.setToolTipText("");

        jTextField1.setName("txt_cod"); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre :");
        jLabel3.setToolTipText("");

        jTextField2.setName("txt_name"); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel4.setText("N° Credito:");
        jLabel4.setToolTipText("");

        jSpinner1.setName("sp_ncredito"); // NOI18N

        jLabel5.setText("Ciclo :");
        jLabel5.setToolTipText("");

        jSpinner2.setName("sp_nciclo"); // NOI18N
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jLabel6.setText("Pre-Requisito :");
        jLabel6.setToolTipText("");

        jTextField3.setName("txt_cod"); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frequena Chuyes\\Dropbox\\PROGRAMAS\\img\\guardar.png")); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setName("btn_guardar"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frequena Chuyes\\Dropbox\\PROGRAMAS\\img\\cancelar.png")); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setName("btn_cancelar"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frequena Chuyes\\Dropbox\\PROGRAMAS\\img\\quitar.png")); // NOI18N
        jButton5.setText("Eliminar");
        jButton5.setName("btn_eliminar"); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jCheckBox1.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(347, 347, 347))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox1)
                                        .addGap(13, 13, 13))
                                    .addComponent(jTextField2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jCheckBox1.getAccessibleContext().setAccessibleName("ch_buscar");
        jCheckBox1.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Lista de Cursos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setComponentPopupMenu(jPopupMenu1);
        jTable2.setEnabled(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frequena Chuyes\\Dropbox\\PROGRAMAS\\img\\descargar.png")); // NOI18N
        jButton3.setText("Cargar");
        jButton3.setName("btn_cargar"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frequena Chuyes\\Dropbox\\PROGRAMAS\\img\\limpiar.png")); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.setName("btn_limpiar"); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("N°=0");
        jLabel8.setToolTipText("");
        jLabel8.setName("lb_nt"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.getAccessibleContext().setAccessibleName("N°=");

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        correcto=1;
        idcurso=null;
        nombre=null;
        ncredito=0;
        ciclo=0;
        prerequisito=null;
        
        try{
        
            if(jTextField1.getText().length()>0 &&
                    jTextField2.getText().length()>0 && 
                    jSpinner1.getValue()!=null &&
                    jSpinner2.getValue()!=null){
                
                if(jTextField1.getText().length()==7){              
                          
                       if(jTextField3.getText().length()>0){
                       
                          if(jTextField3.getText().length()!=7){
                              
                              JOptionPane.showMessageDialog(null,"Pre-Requisito tiene que ser de 7 caracteres...", "Advertencia", JOptionPane.INFORMATION_MESSAGE);                 
                              correcto=0;
                          }                          
                       }                       
                       if((int)jSpinner1.getValue()<=0){
                           
                              JOptionPane.showMessageDialog(null,"N°de creditos debe ser mayor a cero...", "Advertencia", JOptionPane.INFORMATION_MESSAGE);                                         
                              correcto=0;
                       }                          
                       if((int)jSpinner2.getValue()<=0){
                           
                              JOptionPane.showMessageDialog(null,"Ciclo debe ser mayor a cero...", "Advertencia", JOptionPane.INFORMATION_MESSAGE);                                         
                              correcto=0;
                       }  
                       if(correcto==1){
 
                           if(ucurso.posicionCodigo(jTextField1.getText())==-1){
                           
                               guardarCurso();
                               
                           }else{
                           
                              actualizaCurso();
                           }
                       }                    
                   
                }else{
                    
                    JOptionPane.showMessageDialog(null,"Código de curso tiene que ser de 7 caracteres...", "Advertencia", JOptionPane.INFORMATION_MESSAGE);                 
                }
            
            }else{
            
                JOptionPane.showMessageDialog(null,"Por favor complete la información solicitada...", "Advertencia", JOptionPane.INFORMATION_MESSAGE);                 
            }            
            
        }catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
            
            // TODO add your handling code here:
            char keyChar = evt.getKeyChar();
            if(jTextField1.getText().length()>=7) {  
                evt.consume();
            }
            
            if (Character.isLowerCase(keyChar)) {
              evt.setKeyChar(Character.toUpperCase(keyChar));
            }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
           
            char keyChar = evt.getKeyChar();
            if(jTextField3.getText().length()>=7) {  
                evt.consume();
            }
            
            if (Character.isLowerCase(keyChar)) {
              evt.setKeyChar(Character.toUpperCase(keyChar));
            }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
            // TODO add your handling code here:
            char keyChar = evt.getKeyChar();
           
            if (Character.isLowerCase(keyChar)) {
              evt.setKeyChar(Character.toUpperCase(keyChar));
            }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:        
        try{
        
            jTextField1.setText("");
            jTextField2.setText("");
            jSpinner1.setValue(0);
            jSpinner2.setValue(0);
            jTextField3.setText(""); 
            jLabel8.setText("NT=0");
            index=-1;
            if(table!=null){
                
                table.getDataVector().removeAllElements();
                table.fireTableDataChanged();
            }          
            jCheckBox1.setSelected(false);
            
        }catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        try{
        
           listarCurso();
            
        }catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
                // TODO add your handling code here:
        try{
        
            if(jTable2!=null){
                
                if(jTable2.getRowCount()>0){
                    
                    if(jTable2.rowAtPoint(evt.getPoint())!=-1){
                        
                        index=Integer.parseInt(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 0).toString())-1;
                        jTextField1.setText(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 1).toString());
                        jTextField2.setText(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 2).toString());
                        jSpinner1.setValue(Integer.parseInt(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 3).toString()));
                        jSpinner2.setValue(Integer.parseInt(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 4).toString()));
                        jTextField3.setText(jTable2.getValueAt(jTable2.rowAtPoint(evt.getPoint()), 5).toString());
                    }
                    
                }
              
            }
            
        }catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }   
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try{
            
            eliminaCurso();
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        
        try{
        
            if(jCheckBox1.isSelected()){
                
                if(evt.getKeyCode() == KeyEvent.VK_ENTER) {

                     if(jTextField2.getText().length()>0){

                         listarCursoxNombre();
                     }
                }
            }
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        
        
        try{
        
            if(jCheckBox1.isSelected()) {               
                 
                 
                 if(jSpinner2.getValue()!=null){
                 
                      //JOptionPane.showMessageDialog(null,"ffff", "Error", JOptionPane.INFORMATION_MESSAGE); 
                     listarCursoxCiclo();
                 }
            }
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }     
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                // TODO add your handling code here:
         try{                
               
               ordenarCursoxNombre();
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         try{        
          
               ordenarCursoxCiclo();
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    /**********************************Mis Metodos************************************/
    
    public void guardarCurso(){
    
        try{
            
            if(JOptionPane.showConfirmDialog(null, "¿Desea registrar curso?")==0){
                                   
              idcurso=jTextField1.getText();
              nombre=jTextField2.getText().toUpperCase();
              ncredito=(int)jSpinner1.getValue();
              ciclo=(int)jSpinner2.getValue();
              prerequisito=jTextField3.getText();
              ucurso.crearCurso(idcurso, nombre, ncredito, ciclo, prerequisito);
                                   
              JOptionPane.showMessageDialog(null,"Agregado correctamente...", "Información", JOptionPane.INFORMATION_MESSAGE);  
              listarCurso();
              
            }
        }catch (HeadlessException ex) {
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }  
    public void actualizaCurso(){
    
        try{
        
            if(index!=-1){
            
                if(JOptionPane.showConfirmDialog(null, "¿Desea actualizar curso?")==0){
                                   
                    idcurso=jTextField1.getText();
                    nombre=jTextField2.getText().toUpperCase();
                    ncredito=(int)jSpinner1.getValue();
                    ciclo=(int)jSpinner2.getValue();
                    prerequisito=jTextField3.getText();
                    ucurso.modificaCurso(index,idcurso, nombre, ncredito, ciclo, prerequisito);

                    JOptionPane.showMessageDialog(null,"Actualizado correctamente...", "Información", JOptionPane.INFORMATION_MESSAGE);  
                    listarCurso();

                }
            }
            
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    
    }
    
    public void eliminaCurso(){
    
        try{
        
            if(index!=-1){
        
                if(JOptionPane.showConfirmDialog(null, "¿Desea elimnar curso?")==0){
                                   
                    
                    ucurso.elimnarCurso(index);
                    JOptionPane.showMessageDialog(null,"Eliminado correctamente...", "Información", JOptionPane.INFORMATION_MESSAGE);  
                    listarCurso();

                }                 
                
            }
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }
    
    public void listarCursoxNombre(){
    
        Object[] arreglo;        
        try{
            
            arreglo=ucurso.reportarCursoxNombre(jTextField2.getText());
            
            if(arreglo!=null){
            
                table=new DefaultTableModel(col,0);               
                jTable2.setModel(table);                
            
                for (Object arr : arreglo) {
                    
                    table.addRow((Object[]) arr);
                }              
                jLabel8.setText("N°="+arreglo.length);
            }
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
        
    }
    
    public void listarCursoxCiclo(){
    
        Object[] arreglo;        
        try{
            
            arreglo=ucurso.reportarCursoxCiclo((int)jSpinner2.getValue());
            
            if(arreglo!=null){
            
                table=new DefaultTableModel(col,0);               
                jTable2.setModel(table);                
            
                for (Object arr : arreglo) {
                    
                    table.addRow((Object[]) arr);
                }              
                jLabel8.setText("N°="+arreglo.length);
            }
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
        
    }
    
    public void listarCurso(){
        
        Object[] arreglo;        
        try{
            
            arreglo=ucurso.reportarCurso();
            
            if(arreglo!=null){
            
                table=new DefaultTableModel(col,0);               
                jTable2.setModel(table);                
            
                for (Object arr : arreglo) {
                    
                    table.addRow((Object[]) arr);
                }              
                jLabel8.setText("N°="+arreglo.length);
            }
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }
    
    public void ordenarCursoxNombre(){
    
        try{           
             
           ucurso.ordenarCursoxNombre();
           listarCurso();
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }
    
    public void ordenarCursoxCiclo(){
    
        try{           
           
           ucurso.ordenarCursoxCiclo();
           listarCurso();
           
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);  
        }
    }
    
    public static boolean isNumeric(String strNum) {
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }
    
    /***************************************************************/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
